volumes:
  financial-manager-db:

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
    volumes:
      - financial-manager-db:/var/lib/postgresql/data